# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-22 11:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acono',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
                ('discharge', models.FloatField()),
            ],
            options={
                'ordering': ['-date'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Aripo',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
                ('discharge', models.FloatField()),
            ],
            options={
                'ordering': ['-date'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Arouca',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
                ('discharge', models.FloatField()),
            ],
            options={
                'ordering': ['-date'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Capriata',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
                ('discharge', models.FloatField()),
            ],
            options={
                'ordering': ['-date'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Caura',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
                ('discharge', models.FloatField()),
            ],
            options={
                'ordering': ['-date'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Damier',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
                ('discharge', models.FloatField()),
            ],
            options={
                'ordering': ['-date'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FuessGauge',
            fields=[
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('river', models.CharField(max_length=80)),
                ('watershed', models.CharField(choices=[('Arima', 'Arima'), ('Aripo', 'Aripo'), ('Arouca', 'Arouca'), ('Caparo', 'Caparo'), ('Caroni Arena Dam', 'Caroni Arena Dam'), ('Caroni Swamp', 'Caroni Swamp'), ('Cedros', 'Cedros'), ('Chaguaramas', 'Chaguaramas'), ('Cipero', 'Cipero'), ('Couva', 'Couva'), ('Cumuto', 'Cumuto'), ('Cunapo', 'Cunapo'), ('Cunupia', 'Cunupia'), ('El Mamo', 'El Mamo'), ('Erin', 'Erin'), ('Guanapo', 'Guanapo'), ('Guapo', 'Guapo'), ('Guaracara', 'Guaracara'), ('Guayamare', 'Guayamare'), ('Hollis', 'Hollis'), ("L'Ebranche", "L'Ebranche"), ('Lower Navet', 'Lower Navet'), ('Madamas', 'Madamas'), ('Maracas', 'Maracas'), ('Maraval', 'Maraval'), ('Marianne', 'Marianne'), ('Matura', 'Matura'), ('Mausica', 'Mausica'), ('Moriquite', 'Moriquite'), ('Moruga', 'Moruga'), ('Nariva', 'Nariva'), ('North Oropouche', 'North Oropouche'), ('Oropuna', 'Oropuna'), ('Ortoire', 'Ortoire'), ('Pilote', 'Pilote'), ('Poole', 'Poole'), ('Port-of-Spain', 'Port-of-Spain'), ('Quare', 'Quare'), ('Rest Caroni Swamp', 'Rest Caroni Swamp'), ('Rest North', 'Rest North'), ('Rest North Oropouche 1', 'Rest North Oropouche 1'), ('Rest North Oropouche 2', 'Rest North Oropouche 2'), ('Rest South', 'Rest South'), ('Rest West', 'Rest West'), ('Salybia', 'Salybia'), ('Santa Cruz', 'Santa Cruz'), ('South Oropouche', 'South Oropouche'), ('Tacarigua', 'Tacarigua'), ('Talparo', 'Talparo'), ('Toco', 'Toco'), ('Tumpuna', 'Tumpuna'), ('Tunapuna', 'Tunapuna'), ('Upper Navet', 'Upper Navet'), ('Yarra', 'Yarra')], max_length=50)),
                ('northing', models.DecimalField(blank=True, decimal_places=8, max_digits=12, null=True)),
                ('easting', models.DecimalField(blank=True, decimal_places=8, max_digits=12, null=True)),
                ('date_comm', models.DateField(blank=True, null=True)),
                ('date_decomm', models.DateField(blank=True, null=True)),
                ('needs_attn', models.BooleanField(default=False)),
                ('remarks', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Guanapo',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
                ('discharge', models.FloatField()),
            ],
            options={
                'ordering': ['-date'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LasCuevas',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
                ('discharge', models.FloatField()),
            ],
            options={
                'ordering': ['-date'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Lluengo',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
                ('discharge', models.FloatField()),
            ],
            options={
                'ordering': ['-date'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Maraval',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
                ('discharge', models.FloatField()),
            ],
            options={
                'ordering': ['-date'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Marianne',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
                ('discharge', models.FloatField()),
            ],
            options={
                'ordering': ['-date'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Matura',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
                ('discharge', models.FloatField()),
            ],
            options={
                'ordering': ['-date'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MeteringSite',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('watershed', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='images/meterings')),
                ('northing', models.DecimalField(blank=True, decimal_places=8, max_digits=12)),
                ('easting', models.DecimalField(blank=True, decimal_places=8, max_digits=12)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Naranjo',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
                ('discharge', models.FloatField()),
            ],
            options={
                'ordering': ['-date'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NorthOropouche',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
                ('discharge', models.FloatField()),
            ],
            options={
                'ordering': ['-date'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Quare',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
                ('discharge', models.FloatField()),
            ],
            options={
                'ordering': ['-date'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Rincon',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
                ('discharge', models.FloatField()),
            ],
            options={
                'ordering': ['-date'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tompire',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
                ('discharge', models.FloatField()),
            ],
            options={
                'ordering': ['-date'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Yarra',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
                ('discharge', models.FloatField()),
            ],
            options={
                'ordering': ['-date'],
                'abstract': False,
            },
        ),
    ]
