# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-19 16:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamflow_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lopinot',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
                ('discharge', models.FloatField()),
            ],
            options={
                'ordering': ['-date'],
                'abstract': False,
            },
        ),
    ]
