# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-22 11:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Abstraction_Point',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('source_type', models.CharField(max_length=80)),
                ('abstraction_period', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('building_no', models.CharField(max_length=20)),
                ('street_name', models.CharField(max_length=80)),
                ('district', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=80)),
                ('rep_first_name', models.CharField(max_length=80)),
                ('rep_last_name', models.CharField(max_length=80)),
                ('rep_email', models.EmailField(max_length=80)),
            ],
        ),
        migrations.AddField(
            model_name='abstraction_point',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='licensing_app.Company'),
        ),
    ]
