# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-19 16:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('licensing_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='abstraction_point',
            name='abstraction_rate',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='abstraction_point',
            name='abstraction_period',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='abstraction_point',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='abstraction_point',
            name='source_type',
            field=models.CharField(choices=[('Rainfall', 'Rainfall'), ('River', 'River'), ('Spring', 'Spring'), ('Well', 'Well')], max_length=80),
        ),
        migrations.DeleteModel(
            name='Company',
        ),
    ]
