# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-22 11:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Caroni',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
                ('rainfall', models.FloatField(blank=True, null=True)),
                ('level', models.FloatField()),
                ('production', models.FloatField(blank=True, null=True)),
                ('pumpRelease', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hillsborough',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
                ('rainfall', models.FloatField(blank=True, null=True)),
                ('level', models.FloatField()),
                ('production', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hollis',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
                ('rainfall', models.FloatField(blank=True, null=True)),
                ('level', models.FloatField()),
                ('production', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Navet',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
                ('rainfall', models.FloatField(blank=True, null=True)),
                ('level', models.FloatField()),
                ('production', models.FloatField(blank=True, null=True)),
                ('lowerPump', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
