# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-22 18:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservoir_app', '0002_auto_20180322_1318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='navet',
            name='lowerPump',
        ),
        migrations.AddField(
            model_name='navet',
            name='pump',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
