# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-22 11:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EdwardTrace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('reading', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
            options={
                'ordering': ['date'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Moka3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('reading', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
            options={
                'ordering': ['date'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Well',
            fields=[
                ('name', models.CharField(max_length=80)),
                ('index_no', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('wellfield', models.CharField(blank=True, max_length=80, null=True)),
                ('depth', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('northing', models.DecimalField(blank=True, decimal_places=8, max_digits=12, null=True)),
                ('easting', models.DecimalField(blank=True, decimal_places=8, max_digits=12, null=True)),
                ('date_comm', models.DateField(blank=True, null=True)),
                ('date_decomm', models.DateField(blank=True, null=True)),
                ('needs_attn', models.BooleanField(default=False)),
                ('remarks', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
