# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-22 15:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('watershed_app', '0001_initial'),
        ('groundwater_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='well',
            name='watershed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='watershed_app.Watershed'),
        ),
    ]
