# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-22 11:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=80)),
                ('year', models.PositiveSmallIntegerField()),
                ('description', models.TextField(blank=True)),
                ('uploaddate', models.DateTimeField(auto_now_add=True)),
                ('bookcover', models.FileField(blank=True, max_length=225, upload_to='documents/covers/')),
                ('document', models.FileField(blank=True, max_length=225, upload_to='documents/')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
