# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-04 15:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0003_auto_20180404_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=512, unique=True),
        ),
    ]
