# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-07-23 15:37
from __future__ import unicode_literals

from django.db import migrations, models
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0005_auto_20180405_1630'),
    ]

    operations = [
        migrations.CreateModel(
            name='SOP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=225)),
                ('slug', models.SlugField()),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('general', 'General'), ('rainfall', 'Rainfall'), ('streamflow', 'Streamflow'), ('groundwater', 'Groundwater'), ('quality', 'Water Quality'), ('gis', 'GIS')], max_length=125)),
                ('text', markdownx.models.MarkdownxField(blank=True, null=True)),
            ],
        ),
    ]
