# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-07-24 19:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0006_sop'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='bar_code',
            new_name='isbn',
        ),
        migrations.RemoveField(
            model_name='book',
            name='call_no',
        ),
        migrations.AddField(
            model_name='book',
            name='slug',
            field=models.SlugField(default='-'),
            preserve_default=False,
        ),
    ]
