# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-07-31 17:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0007_auto_20180724_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('Unavailable', 'Unavailable'), ('Reference', 'Reference')], default='Available', max_length=80),
            preserve_default=False,
        ),
    ]
