# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-22 15:28
from __future__ import unicode_literals

from django.db import migrations, models
import markdownx.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Watershed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('hydrometric_area', models.PositiveSmallIntegerField(choices=[(1, 'North Coast'), (2, 'North Oropouche'), (3, 'Nariva'), (4, 'Ortoire'), (5, 'Southern Range'), (6, 'Cedros Peninsula'), (7, 'South Oropouche'), (8, 'Central West Coast'), (9, 'Western Peninsula')])),
                ('area', models.FloatField()),
                ('description', markdownx.models.MarkdownxField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
