# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-07-20 12:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watershed_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watershed',
            name='hydrometric_area',
            field=models.PositiveSmallIntegerField(choices=[(1, 'North Coast'), (2, 'North Oropouche'), (3, 'Nariva'), (4, 'Ortoire'), (5, 'Southern Range'), (6, 'Cedros Peninsula'), (7, 'South Oropouche'), (8, 'Central West Coast'), (9, 'Western Peninsula'), (11, 'Leeward'), (12, 'East Coast'), (13, 'Windward'), (14, 'Courland'), (15, 'Lowlands')]),
        ),
    ]
