# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-07-24 19:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watershed_app', '0002_auto_20180720_0812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watershed',
            name='slug',
            field=models.SlugField(),
        ),
    ]
