CATEGORY = (
    ('Pot', 'Pot Gauge'),
    ('HOBO', 'HOBO'),
    ('Telemet', 'Telemet'),
    ('Lambredt', 'Lambredt'),
)

WATERSHEDS = (
    ('Arima', 'Arima'),
    ('Aripo', 'Aripo'),
    ('Arouca', 'Arouca'),
    ('Caparo', 'Caparo'),
    ('Caroni Arena Dam', 'Caroni Arena Dam'),
    ('Caroni Swamp', 'Caroni Swamp'),
    ('Cedros', 'Cedros'),
    ('Chaguaramas', 'Chaguaramas'),
    ('Cipero', 'Cipero'),
    ('Couva', 'Couva'),
    ('Cumuto', 'Cumuto'),
    ('Cunapo', 'Cunapo'),
    ('Cunupia', 'Cunupia'),
    ('El Mamo', 'El Mamo'),
    ('Erin', 'Erin'),
    ('Guanapo', 'Guanapo'),
    ('Guapo', 'Guapo'),
    ('Guaracara', 'Guaracara'),
    ('Guayamare', 'Guayamare'),
    ('Hollis', 'Hollis'),
    ("L'Ebranche", "L'Ebranche"),
    ('Lower Navet', 'Lower Navet'),
    ('Madamas', 'Madamas'),
    ('Maracas', 'Maracas'),
    ('Maraval', 'Maraval'),
    ('Marianne', 'Marianne'),
    ('Matura', 'Matura'),
    ('Mausica', 'Mausica'),
    ('Moriquite', 'Moriquite'),
    ('Moruga', 'Moruga'),
    ('Nariva', 'Nariva'),
    ('North Oropouche', 'North Oropouche'),
    ('Oropuna', 'Oropuna'),
    ('Ortoire', 'Ortoire'),
    ('Pilote', 'Pilote'),
    ('Poole', 'Poole'),
    ('Port-of-Spain', 'Port-of-Spain'),
    ('Quare', 'Quare'),
    ('Rest Caroni Swamp', 'Rest Caroni Swamp'),
    ('Rest North', 'Rest North'),
    ('Rest North Oropouche 1', 'Rest North Oropouche 1'),
    ('Rest North Oropouche 2', 'Rest North Oropouche 2'),
    ('Rest South', 'Rest South'),
    ('Rest West', 'Rest West'),
    ('Salybia', 'Salybia'),
    ('Santa Cruz', 'Santa Cruz'),
    ('South Oropouche', 'South Oropouche'),
    ('Tacarigua', 'Tacarigua'),
    ('Talparo', 'Talparo'),
    ('Toco', 'Toco'),
    ('Tumpuna', 'Tumpuna'),
    ('Tunapuna', 'Tunapuna'),
    ('Upper Navet', 'Upper Navet'),
    ('Yarra', 'Yarra'),
)
