# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-07-12 18:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArenaPlantation',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
                ('rainfall', models.FloatField()),
            ],
            options={
                'ordering': ['date'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AsaWright',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
                ('rainfall', models.FloatField()),
            ],
            options={
                'ordering': ['date'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BlanchisseusePolice',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
                ('rainfall', models.FloatField()),
            ],
            options={
                'ordering': ['date'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BotanicGardens',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
                ('rainfall', models.FloatField()),
            ],
            options={
                'ordering': ['date'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BrassoParia',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
                ('rainfall', models.FloatField()),
            ],
            options={
                'ordering': ['date'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ChathamGovernment',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
                ('rainfall', models.FloatField()),
            ],
            options={
                'ordering': ['date'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ColumbiaEstate',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
                ('rainfall', models.FloatField()),
            ],
            options={
                'ordering': ['date'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ConstanceEstate',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
                ('rainfall', models.FloatField()),
            ],
            options={
                'ordering': ['date'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CumanaVillage',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
                ('rainfall', models.FloatField()),
            ],
            options={
                'ordering': ['date'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CumutoPine',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
                ('rainfall', models.FloatField()),
            ],
            options={
                'ordering': ['date'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ElSusanEstate',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
                ('rainfall', models.FloatField()),
            ],
            options={
                'ordering': ['date'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FishingPond',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
                ('rainfall', models.FloatField()),
            ],
            options={
                'ordering': ['date'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FreeportWaterworks',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
                ('rainfall', models.FloatField()),
            ],
            options={
                'ordering': ['date'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GaugeReader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=45)),
                ('last_name', models.CharField(max_length=80)),
                ('phone', models.PositiveIntegerField()),
                ('house_no', models.CharField(max_length=20)),
                ('street_name', models.CharField(max_length=80)),
                ('town', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='GordonMiller',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
                ('rainfall', models.FloatField()),
            ],
            options={
                'ordering': ['date'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GranvilleWaterworks',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
                ('rainfall', models.FloatField()),
            ],
            options={
                'ordering': ['date'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GrosnevorEstate',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
                ('rainfall', models.FloatField()),
            ],
            options={
                'ordering': ['date'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Hollis',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
                ('rainfall', models.FloatField()),
            ],
            options={
                'ordering': ['date'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LaRegalada',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
                ('rainfall', models.FloatField()),
            ],
            options={
                'ordering': ['date'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MarperFarm',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
                ('rainfall', models.FloatField()),
            ],
            options={
                'ordering': ['date'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MatelotRestHouse',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
                ('rainfall', models.FloatField()),
            ],
            options={
                'ordering': ['date'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MaturaPolice',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
                ('rainfall', models.FloatField()),
            ],
            options={
                'ordering': ['date'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MelajoPlantation',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
                ('rainfall', models.FloatField()),
            ],
            options={
                'ordering': ['date'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Navet',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
                ('rainfall', models.FloatField()),
            ],
            options={
                'ordering': ['date'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NavetPresbyterian',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
                ('rainfall', models.FloatField()),
            ],
            options={
                'ordering': ['date'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Newlands',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
                ('rainfall', models.FloatField()),
            ],
            options={
                'ordering': ['date'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrtoireEstate',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
                ('rainfall', models.FloatField()),
            ],
            options={
                'ordering': ['date'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PenalWaterworks',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
                ('rainfall', models.FloatField()),
            ],
            options={
                'ordering': ['date'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PerseveranceEstate',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
                ('rainfall', models.FloatField()),
            ],
            options={
                'ordering': ['date'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Petrotrin',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
                ('rainfall', models.FloatField()),
            ],
            options={
                'ordering': ['date'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Piarco',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
                ('rainfall', models.FloatField()),
            ],
            options={
                'ordering': ['date'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PointFortinWTP',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
                ('rainfall', models.FloatField()),
            ],
            options={
                'ordering': ['date'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Pure',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
                ('rainfall', models.FloatField()),
            ],
            options={
                'ordering': ['date'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RainGauge',
            fields=[
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('Pot', 'Pot Gauge'), ('HOBO', 'HOBO'), ('Telemet', 'Telemet'), ('Lambredt', 'Lambredt')], max_length=45)),
                ('serial_no', models.CharField(blank=True, max_length=45, null=True)),
                ('watershed', models.CharField(choices=[('Arima', 'Arima'), ('Aripo', 'Aripo'), ('Arouca', 'Arouca'), ('Caparo', 'Caparo'), ('Caroni Arena Dam', 'Caroni Arena Dam'), ('Caroni Swamp', 'Caroni Swamp'), ('Cedros', 'Cedros'), ('Chaguaramas', 'Chaguaramas'), ('Cipero', 'Cipero'), ('Couva', 'Couva'), ('Cumuto', 'Cumuto'), ('Cunapo', 'Cunapo'), ('Cunupia', 'Cunupia'), ('El Mamo', 'El Mamo'), ('Erin', 'Erin'), ('Guanapo', 'Guanapo'), ('Guapo', 'Guapo'), ('Guaracara', 'Guaracara'), ('Guayamare', 'Guayamare'), ('Hollis', 'Hollis'), ("L'Ebranche", "L'Ebranche"), ('Lower Navet', 'Lower Navet'), ('Madamas', 'Madamas'), ('Maracas', 'Maracas'), ('Maraval', 'Maraval'), ('Marianne', 'Marianne'), ('Matura', 'Matura'), ('Mausica', 'Mausica'), ('Moriquite', 'Moriquite'), ('Moruga', 'Moruga'), ('Nariva', 'Nariva'), ('North Oropouche', 'North Oropouche'), ('Oropuna', 'Oropuna'), ('Ortoire', 'Ortoire'), ('Pilote', 'Pilote'), ('Poole', 'Poole'), ('Port-of-Spain', 'Port-of-Spain'), ('Quare', 'Quare'), ('Rest Caroni Swamp', 'Rest Caroni Swamp'), ('Rest North', 'Rest North'), ('Rest North Oropouche 1', 'Rest North Oropouche 1'), ('Rest North Oropouche 2', 'Rest North Oropouche 2'), ('Rest South', 'Rest South'), ('Rest West', 'Rest West'), ('Salybia', 'Salybia'), ('Santa Cruz', 'Santa Cruz'), ('South Oropouche', 'South Oropouche'), ('Tacarigua', 'Tacarigua'), ('Talparo', 'Talparo'), ('Toco', 'Toco'), ('Tumpuna', 'Tumpuna'), ('Tunapuna', 'Tunapuna'), ('Upper Navet', 'Upper Navet'), ('Yarra', 'Yarra')], max_length=50)),
                ('northing', models.DecimalField(blank=True, decimal_places=8, max_digits=12, null=True)),
                ('easting', models.DecimalField(blank=True, decimal_places=8, max_digits=12, null=True)),
                ('date_comm', models.DateField(blank=True, null=True)),
                ('date_decomm', models.DateField(blank=True, null=True)),
                ('needs_attn', models.BooleanField(default=False)),
                ('remarks', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RiverEstate',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
                ('rainfall', models.FloatField()),
            ],
            options={
                'ordering': ['date'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SanAntonio',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
                ('rainfall', models.FloatField()),
            ],
            options={
                'ordering': ['date'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SanAntonioEstate',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
                ('rainfall', models.FloatField()),
            ],
            options={
                'ordering': ['date'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SanJuan',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
                ('rainfall', models.FloatField()),
            ],
            options={
                'ordering': ['date'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SanPedroEstate',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
                ('rainfall', models.FloatField()),
            ],
            options={
                'ordering': ['date'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SanQuintinEstate',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
                ('rainfall', models.FloatField()),
            ],
            options={
                'ordering': ['date'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SansSouci',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
                ('rainfall', models.FloatField()),
            ],
            options={
                'ordering': ['date'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SantaMariaEstate',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
                ('rainfall', models.FloatField()),
            ],
            options={
                'ordering': ['date'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SinghsEstate',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
                ('rainfall', models.FloatField()),
            ],
            options={
                'ordering': ['date'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TCLClaxtonBay',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
                ('rainfall', models.FloatField()),
            ],
            options={
                'ordering': ['date'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TCLMayo',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
                ('rainfall', models.FloatField()),
            ],
            options={
                'ordering': ['date'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Torrecilla',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
                ('rainfall', models.FloatField()),
            ],
            options={
                'ordering': ['date'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TortugaEstate',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
                ('rainfall', models.FloatField()),
            ],
            options={
                'ordering': ['date'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TrinidadLakeAsphalt',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
                ('rainfall', models.FloatField()),
            ],
            options={
                'ordering': ['date'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UWI',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
                ('rainfall', models.FloatField()),
            ],
            options={
                'ordering': ['date'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UWIFieldStation',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
                ('rainfall', models.FloatField()),
            ],
            options={
                'ordering': ['date'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ValenciaRange',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
                ('rainfall', models.FloatField()),
            ],
            options={
                'ordering': ['date'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='gaugereader',
            name='gauge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data_app.RainGauge'),
        ),
    ]
